version: 0.6.0.{build}
branches:
  except:
  - wiki-content
  - gh-pages
skip_tags: true
configuration:
- Debug
- Release
platform:
- x86
# - x64
clone_folder: c:\projects\kate
init:
- cmd: git config --global core.autocrlf "false"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: cinst cs-script -y
before_build:
- cmd: nuget restore
build:
  project: NppKate.sln
  parallel: true
  verbosity: quiet
after_build:
- cmd: cscs build\KatePack.cs
artifacts:
- path: bin\$(ZIP_NAME)
  name: ARCHIVE-BUILD
deploy: off
notifications:
- provider: Email
  to:
  - schadin@gmail.com
  subject: Build success
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - schadin@gmail.com
  subject: Build failure
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false